PORT: "8000"
GITHUB_API_URL: "https://api.github.com/search/users"
DEFAULT_PAGE: 0
DEFAULT_PER_PAGE: 10
TWITTER_CONSUMER_KEY: "6i053ZksGroBPZl7DYy6Sfb2x"
TWITTER_CONSUMER_SECRET: "jogpdqPmjT2Wq7UcIHB42rZ8jyPEoaz4UQM0ezpeL7gEwMGJzY"
TWITTER_ACCESS_TOKEN: "2684164752-1zso52cUIEq1qqSQcXk5gMllCbp2XfnoBJna7yk"
TWITTER_ACCESS_TOKEN_SECRET: "dmVZIeQSOwyBU2lPILbnG6wzQ02iWoKEvPlxHZvDVrYfd"
DB_USER: "postgres"
DB_PASSWORD: "postgres"
DB_NAME: "profilopedia_development"
